---
name: Double Duty (Analog)
description: |
  # Double Duty (Analog)
  An analog circuit that separates Left, Right and Microhpone Channels

  Allows you to connect headphones to multiple computers/phones and quickly switch between them.

  E.g.
  Left Channel: Computer 1
  Right Channel: Computer 2
  Microphone: Phone 1

  Inspired by the [Little Bear 104](Nobsound Little Bear MC104), but improved by adding a microphone channel.

  ## Components
  - [6X PJ-320 3.5mm Jacks](https://a.co/d/i1pVVkF)
  - [3X SR16 Rotary Switches](https://www.adafruit.com/product/2925)
  - [1x 8x8 DPDT Push Button Switch (Locking)](https://a.co/d/0V0eQZa)

  These switches have mixed reviews. Shop around for higher quality switches. 
  You may need a 3d printer to print a button for the switch. 

  ## Manufacture

  Gerber files are available in the CAD folder. 
  You can upload the gerber to your favorite PCB manufacture to order PCBS

  - JLCPCB
  - PCBWay
  - OSH Park


  ## Assembly

  The CAD directory contains PDFs which can be used to make your own PCB at home using the toner transfer method. 
  See VIAS.pdf for highlights of which pads need via connections (use thin wire).

  You will also need a drill press.

  ### Recommended Tools
  - [Dremel Workstation ($50)](https://a.co/d/hqsWSRO)
  - [ApexForge Dremel ($35)](https://a.co/d/0IppCuM)
  - [Harbor Freight Micro Drill Bits ($3)](https://www.harborfreight.com/power-tools/drill-driver-bits/high-speed-steel-micro-drill-bit-set-30-piece-61526.html)

  - [Copper Etchant ($12)](https://a.co/d/jed4hNp)
  - Baking Soda
  - [Toner Transfer Paper (free from vinyl wrap)](https://youtu.be/haqP8xhsYas?t=112)
  - [70x100cm PCB Board ($10)](https://a.co/d/b2f2wr8)
  - Latex Gloves
  - Respirator
  - Safety Glasses
  - Kaptan Tape

  Note: Early versions require an 80x100cm board. You will need to cut your own board to size. 
  70x100cm boards wll not work for earlier versions

license: 
  type: CC-Attribution # MIT, GPL, CC-Attribution, CC-Attribution-NoDerivs, CC-Attribution-ShareAlike, CC-Attribution-NonCommercial, CC-Attribution-NC-SA
  owner: Spencer Owen
  year: 2022
# resources:
#   foo: https://example.com
# fusion_link: https://autodesk.example.com #comment out if no fusion link
# links:
#   Thingiverse: https://www.thingiverse.com/thing:xxxx
#   Printables: https://foo.com
#   GrabCad: https://foo.com
#   Hackster.io: https://hackster.io/foo
#   Hackaday: https://hackaday.io/foo
#   Reddit: https://www.reddit.com/r/foo
#   Github: https://github.com/foo
#   Blog: https://foo.com
